name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Run tests, output coverage
      run: |
        npm ci
        npm run test:coverage
        npm run test:badges
    - name: Read coverage output
      run: |
        json_get () {
          echo $(jq ".total.$1.pct" coverage/coverage-summary.json)
        }

        COVERAGE_LINES=`json_get lines`
        COVERAGE_STATEMENTS=`json_get statements`
        COVERAGE_FUNCTIONS=`json_get functions`
        COVERAGE_BRANCHES=`json_get branches`
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Create the Badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_TOKEN }}
        gistID: 17ea5fefe3b3fc7fe430382821173e13
        filename: unspoken-${{ steps.extract_branch.outputs.branch }}.json
        label: Test Coverage
        message: ${{ env.COVERAGE }}
        color: green
        namedLogo: jest
